[package]
name = "kyocera-printer-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
indicatif = "0.17.8"
phf = { version = "0.11.2", features = ["macros"] }
reqwest = "0.12.3"
serde_json = "1.0.115"
tokio = "1.37.0"
v8 = "0.91.0"
