[package]
name = "kyocera-printer-monitor"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
arboard = { version = "3.3.2", default-features = false }
deno_core = "0.278.0"
indicatif = "0.17.8"
phf = { version = "0.11.2", features = ["macros"] }
reqwest = { version = "0.12.4" }
semver = "1.0.22"
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = ["full"] }
