[package]
name = "kyocera-printer-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
arboard = { version = "3.3.2", default-features = false }
deno_core = "0.276.0"
indicatif = "0.17.8"
phf = { version = "0.11.2", features = ["macros"] }
reqwest = "0.12.3"
serde_json = "1.0.115"
tokio = { version = "1.37.0", features = ["full"] }
