on:
  workflow_dispatch:

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: kyocera-printer-monitor
            name: kyocera-printer-monitor-x86_64-unknown-linux-gnu.tar.gz
            command: build

          - release_for: Linux-ARM
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            bin: kyocera-printer-monitor
            name: kyocera-printer-monitor-aarch64-unknown-linux-gnu.tar.gz
            command: build

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: precious.exe
            name: kyocera-printer-monitor-x86_64-pc-windows-msvc.zip
            command: build

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: precious
            name: kyocera-printer-monitor-x86_64-apple-darwin.tar.gz
            command: build

          - release_for: macOS-ARM
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: precious
            name: kyocera-printer-monitor-aarch64-apple-darwin.tar.gz
            command: build

            # more release targets here ...

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
#        run: rustup toolchain install nightly --profile minimal
        uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
          toolchain: nightly