name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: ${{ github.event.repository.name }}-x86_64-unknown-linux-gnu
            name: ${{ github.event.repository.name }}-x86_64-unknown-linux-gnu
            command: build

          - release_for: Linux-ARM
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            bin: ${{ github.event.repository.name }}-aarch64-unknown-linux-gnu
            name: ${{ github.event.repository.name }}-aarch64-unknown-linux-gnu
            command: build

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: ${{ github.event.repository.name }}-x86_64-pc-windows-msvc.exe
            name: ${{ github.event.repository.name }}-x86_64-pc-windows-msvc.exe
            command: build

          - release_for: Windows-ARM
            os: windows-latest
            target: aarch64-pc-windows-msvc
            bin: ${{ github.event.repository.name }}-aarch64-pc-windows-msvc.exe
            name: ${{ github.event.repository.name }}-aarch64-pc-windows-msvc.exe
            command: build

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: ${{ github.event.repository.name }}-x86_64-apple-darwin
            name: ${{ github.event.repository.name }}-x86_64-apple-darwin
            command: build

          - release_for: macOS-ARM
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: ${{ github.event.repository.name }}-aarch64-apple-darwin
            name: ${{ github.event.repository.name }}-aarch64-apple-darwin
            command: build

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.platform.target }}  # not sure if this is necessary but it makes me sleep at night
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
          toolchain: nightly
      - name: Publish release artifacts
        uses: actions/upload-artifact@v4
        with:
          # github forces these to be a zip which is dumb but whatever might as well embrace it,,,
          name: ${{ matrix.platform.name }}
          path: "./target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}"
  zip_and_upload:
    name: Zip and Upload
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Unzip artifacts
        run: |
          mkdir unzipped
          for file in ./artifacts/*.zip; do
            unzip -o "$file" -d ./unzipped
          done

      - name: Zip all files
        run: zip -r aggregate.zip ./unzipped

      - name: Upload final zip
        uses: actions/upload-artifact@v4
        with:
          name: aggregate
          path: aggregate.zip